//SERVERS ERROS
export const STATUS_INTERNAL_SERVER_ERROR = 500
export const STATUS_BAD_GATEWAY = 502
export const STATUS_NETWORD_AUTHENTICATION_REQUIRED = 511

//SUCCESS
export const STATUS_OK = 200
export const STATUS_CREATED = 201
export const STATUS_NOT_CONTENT = 204
export const STATUS_PARTIAL_CONTENT = 206

//ERROR CLIENT
export const STATUS_BAD_REQUEST = 400
export const STATUS_UNAUTHORIZED = 401
export const STATUS_FORBIDDEN = 403
export const STATUS_CONFLICT = 409
